trigger:
  branches:
    include:
    - 'main'  

## Development environment
## Build
stages:
- stage: Build_Development
  displayName: Build Development
  condition: startsWith(variables['build.sourceBranch'], 'refs/heads/main')    
  variables:      
    - group: dojo.dev
  jobs:    
    - job: build
      displayName: Build and Generate Migrations
      pool:
        vmImage: windows-latest    
    
      steps:       
        - template: templates/generate-inventory-migration.yml
          parameters:
            environment: Development
          
# Run migrations  
- stage: Dev
  dependsOn: 
    - Build_Development
  condition:  and(succeeded('Build_Development'), startsWith(variables['build.sourceBranch'], 'refs/heads/main') )


  displayName: Run Migration to Dev
  jobs:    
    - template:  templates/run-inventory-migrations-template.yml
      parameters:    
        environmentVariableGroup: dojo.dev
        environment: Development
        azureSubscription: 'dojo-snc(1)(bc6fc020-fffa-4ace-9100-0065f1bce58d)'
        vmImage: 'windows-latest'  
